### ISSUE TITLE
[TASKS] Issues Encountered (Backlog)

### ISSUE THREAD

**Issue by jedpedregosa** [jedpedregosa/BespeakDevelopment#15]
- [ ] When signing out ```on code``` an error message occurs (For Investigation):
`[auth/no-current-user] No user currently signed in.
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke - ... 9 more stack frames from framework internals`

- [x] When signing in (For Investigation):
```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. ```

- [ ] [ON EDIT PROFILE] Optimize image picker, add more validation, catch possible errors.
- [ ] [ALL] Catch Possible Internet Errors.

**Comment by KyleMiguelLaurente** [comment]
Edit Profile > Input Fields
 Di' mapalitan delete or add character.
